# Generated by Django 2.2.3 on 2019-09-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20190803_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentKey', models.IntegerField(default=10)),
            ],
        ),
    ]
