# Generated by Django 2.2.3 on 2019-09-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_currentkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingkey',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
