# Generated by Django 2.2.3 on 2019-09-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_meetingkey_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingkey',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='meetingKey/'),
        ),
    ]
